# Generated by Django 5.1.1 on 2025-07-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='area',
            name='ux_nombre_area',
        ),
        migrations.AddField(
            model_name='departamento',
            name='mail_departamento',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='mail_jefe_departamento',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
