# Generated by Django 4.2.1 on 2025-07-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_add_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturadocente',
            name='cargo',
            field=models.CharField(choices=[('AUX DOC DE PRIMERA', 'AUX DOC DE PRIMERA'), ('AUX DOCENTE SEGUNDA', 'AUX DOCENTE SEGUNDA'), ('Categoria 01 Dto.366', 'Categoria 01 Dto.366'), ('Categoria 02 Dto.366', 'Categoria 02 Dto.366'), ('Categoria 03 Dto.366', 'Categoria 03 Dto.366'), ('Categoria 04 Dto.366', 'Categoria 04 Dto.366'), ('Categoria 05 Dto.366', 'Categoria 05 Dto.366'), ('Categoria 06 Dto.366', 'Categoria 06 Dto.366'), ('Categoria 07 Dto.366', 'Categoria 07 Dto.366'), ('DECANO FACULTAD', 'DECANO FACULTAD'), ('JEFE TRABAJOS PRACT.', 'JEFE TRABAJOS PRACT.'), ('PROFESOR ADJUNTO', 'PROFESOR ADJUNTO'), ('PROFESOR ASOCIADO', 'PROFESOR ASOCIADO'), ('PROFESOR TITULAR', 'PROFESOR TITULAR'), ('SECRETARIO FACULTAD', 'SECRETARIO FACULTAD'), ('VICE DECANO', 'VICE DECANO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='asignaturadocente',
            name='condicion',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Interino', 'Interino'), ('Transitorio', 'Transitorio'), ('Licencia sin goce de sueldo', 'Licencia sin goce de sueldo'), ('Renuncia', 'Renuncia'), ('Licencia con goce de sueldo', 'Licencia con goce de sueldo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='asignaturadocente',
            name='dedicacion',
            field=models.CharField(choices=[('EXCL', 'EXCL'), ('SIMP', 'SIMP'), ('SEMI', 'SEMI'), ('35HS', '35HS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asignaturadocente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
