# Generated by Django 5.1.1 on 2025-07-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='legajo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Legajo'),
        ),
    ]
